### ISSUE TITLE
[Story] User registration 

### ISSUE THREAD

**Issue by halsk** [codeforjapan/hackdays#5]
## Goal:

As a project leader, I want to register for the service So that I can manage my projects

## Tasks:

1.  Add OAuth settings on the supabase (GitHub Auth so far)
2. Add client-side code
3. Check the way to test locally.
4. Update documents
 
## Acceptance Criteria:

- [ ] Users can register via GitHub
- [ ] Users can register via GitHub
- [ ] Users can sign in
- [ ] Users can sign out
- [ ] Users can delete their account
- [ ] Users can register via email/password
- [ ] Users can register via email/password
- [ ] Users can register via Twitter
- [ ] Users can register via Twitter
- [ ] Users can register via Facebook
- [ ] Users can register via Facebook

**Comment by halsk** [comment]
Deleting users needs to be considered how we have to handle the projects and activities that the user associated.
I created #12, and I skip the implementation of the feature so far.
